### ISSUE TITLE
[Discussion] Tech stack

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/tap#1]
We look forward to building the TAP cell website with the MERN stack. Reasons:

- NodeJs is the most popular platform for developing web applications along with a humongous developer community.
- React will help us create a great frontend due to the sheer number of tutorials and workflows facilitating the library.
- Express is robust enough for the job, setting it up takes similar requirements as of React.
- The data we'll be using on this website won't contain a lot of inter-relations, thus we go for NoSQL db. MongoDB is the prime choice due to [`mongoose`](https://mongoosejs.com) which can easily be used in Express.

**Comment by tusharjain0022** [comment]
Discussion done, In place React .js we will be using Next.js as per discussion,everything else is same
