### ISSUE TITLE
[frontend] Create Footer

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/tap#16]
### Description
- Create Footer as per the designs
- Use Material UI library if needed (for icons and styling)
- Make it responsive for all screen sizes
- Try to document your work (on google docs, confluence, etc)

### Design Link 
https://www.figma.com/file/PirkAacPlD2VdZAIrrqlY3/iiitr?node-id=0%3A1

### Screenshots/testimonials
![Screenshot from 2022-01-02 19-41-05](https://user-images.githubusercontent.com/59157988/147881844-01862aaa-7f5b-4866-a1c8-28939cbb33cd.png)

**Comment by abhishekrathi16** [comment]
I would like to take this up

**Comment by EmperorYP7** [comment]
Closing against #21
