### ISSUE TITLE
[frontend] Create Navbar

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/tap#17]
### Description
- Create FooterNavbar as per the designs
- Use Material UI library if needed (for icons and styling)
- Make it responsive for all screen sizes
- Try to document your work (on google docs, confluence, etc)

### Design Link 
https://www.figma.com/file/PirkAacPlD2VdZAIrrqlY3/iiitr?node-id=0%3A1

### Screenshots/testimonials
![Screenshot from 2022-01-02 19-45-51](https://user-images.githubusercontent.com/59157988/147882024-4679bdb3-a0ac-44fe-9074-e5a2c2991a09.png)

**Comment by utkarsh0908** [comment]
Working on the issue, please assign it to me

**Comment by SrijanSriv** [comment]
Closing against #19.
