### ISSUE TITLE
[Bots] Add @all-contributors

### ISSUE THREAD

**Issue by EmperorYP7** [houseofgeeks/tap#25]
### Description
<write your description> Add [all-contributors](https://github.com/all-contributors/all-contributors) to the project for appreciating individuals who give time and efforts in making this project.

### Reference

You may refer to [this commit](https://github.com/houseofgeeks/hg/commit/6f6f5b794dafdb91937aa962bf40fed59c4861f4) from houseofgeeks/hg

**Comment by tusharjain0022** [comment]
closing this as bot is already added
