### ISSUE TITLE
[front-end] Code the landing Page + Navbar

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/tap#29]
### Description
- Code the Landing Page + Navbar as per the deisgn
-  Discuss in the group before adding any new npm library
Note - Ask Satyam for design-related doubts.

Design Link 
https://www.figma.com/file/PirkAacPlD2VdZAIrrqlY3/iiitr?node-id=0%3A1

### Screenshots/testimonials
![Screenshot from 2022-02-16 18-44-59](https://user-images.githubusercontent.com/59157988/154272196-c9464bab-6dcd-47f7-bab5-5f009326aaee.png)

**Comment by himanishu-2512** [comment]
Lorem Ipsum

**Comment by RaiAbhinavPrakash** [comment]
Lorem Ipsum

**Comment by LokeshRM** [comment]
Lorem ipsum dolor

**Comment by NaitikMishra** [comment]
yeah, ready to join

**Comment by SrijanSriv** [comment]
closing against #35, #34 and #32
